### ISSUE TITLE
Bug with parsing 3 decimal places

### ISSUE THREAD

**Issue by jekozyra** [mktj/parsecurrency#14]
According to the lib + tests, parsing a value with 3 decimal places should return null. However, I'm getting a value back.

```
parseCurrency('€55.555') => 
{
      raw: '€55.555',
      value: 55555,
      integer: '55.555',
      decimals: '',
      currency: '',
      symbol: '€',
      decimalSeparator: '',
      groupSeparator: '.',
      sign: ''
}
```

**Comment by mktj** [comment]
Hello @jekozyra!

This is by design and a current limitation of the library. See this test:
```
    expect(parseCurrency('€10.000,00 EUR')).to.deep.equal({
      raw: '€10.000,00 EUR',
      value: 10000.00,
      integer: '10.000',
      decimals: ',00',
      currency: 'EUR',
      symbol: '€',
      decimalSeparator: ',',
      groupSeparator: '.',
      sign: ''
    });
```

Your example is the same, except without the decimals. In your example, the `.` could be interpreted either as a group separator or a decimal point. The library assumes the number is valid and the dot is a group separator.
